security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path: /logout
                target: /
            anonymous: ~
